---

- name: remove MySQL 5.1
  yum: name=mysql-libs state=absent

- name: install MySQL 5.5
  yum: name={{ item }} state=present enablerepo=remi
  with_items:
    - mysql
    - mysql-devel
    - mysql-server
    - mysql-utilities

- name: copy the my.cnf file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysqld

- name: install MySQL-python
  yum: name=MySQL-python state=present

- name: ensure MySQL service is started and enabled at boot
  service: name=mysqld state=started enabled=yes

- name: change MySQL root user's password
  mysql_user: name=root password={{ mysql.root_password }} host=localhost
  sudo: no

- name: configure MySQL database
  template: src=mysql_user.my.cnf.j2 dest=~/.my.cnf
  sudo: no
