---

- name: remove MySQL 5.1
  yum: name=mysql-libs state=absent
  sudo: true

- name: install MySQL 5.5
  yum: name={{ item }} state=present enablerepo=remi
  with_items:
    - mysql
    - mysql-devel
    - mysql-server
    - mysql-utilities
  sudo: true

- name: copy the my.cnf file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysqld
  sudo: true

- name: install MySQL-python
  yum: name=MySQL-python state=present
  sudo: true

- name: ensure MySQL service is started and enabled at boot
  service: name=mysqld state=started enabled=yes
  sudo: true

- name: change MySQL root user's password
  mysql_user: name=root password={{ mysql.root_password }} host=localhost

- name: configure MySQL database
  template: src=mysql_user.my.cnf.j2 dest=/home/{{ remote_user }}/.my.cnf
