---
- name: start cassandra
  service: name=cassandra state=started

- name: restart cassandra
  service: name=cassandra state=restarted

- name: stop cassandra
  service: name=cassandra state=stopped
