---
- name: download tmux source
  get_url:
    url=https://github.com/tmux/tmux/releases/download/{{ tmux.version }}/tmux-{{ tmux.version }}.tar.gz
    dest="{{ src_dir }}/tmux-{{ tmux.version }}.tar.gz"

- name: extract tmux source
  unarchive:
    src="{{ src_dir }}/tmux-{{ tmux.version }}.tar.gz"
    dest="{{ src_dir }}"
    copy=no

- name: install tmux
  shell: >
    {{ item }}
    chdir="{{ src_dir }}/tmux-{{ tmux.version }}"
    creates="{{ bin_dir }}/tmux"
  with_items:
    - ./configure
    - make
    - make install
