---
- name: copy the datastax.repo
  template: src=datastax.repo.j2 dest=/etc/yum.repos.d/datastax.repo

- name: install cassandra22
  yum: name={{ item }} state=present enablerepo=datastax
  with_items:
    - dsc22
    - cassandra22-tools

- name: ensure cassandra service is started and enabled at boot
  service: name=cassandra state=started enabled=yes
