---

- name: install nginx repo
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
       state=present
  sudo: true

- name: install nginx
  yum: name=nginx state=present enablerepo=nginx
  sudo: true
