---
- name: install maven repo
  get_url:
    url=http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
    dest=/etc/yum.repos.d/epel-apache-maven.repo

- name: sed maven repo
  shell: sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo

- name: install maven
  yum: name=apache-maven state=present enablerepo=epel-apache-maven
